language: go

go:
- 1.12.x

install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
- go get github.com/go-playground/overalls
- go get github.com/tebeka/selenium
- go get github.com/autograde/kit/score

env:
- GO111MODULE=on GOFLAGS='-mod vendor'

script:
- $HOME/gopath/bin/overalls -project=github.com/autograde/aguis -covermode=count -debug
- $HOME/gopath/bin/goveralls -coverprofile=overalls.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN
