version: '3.8'
services:
  envoy:
    container_name: envoy
    image: quickfeed/envoy
    build:
      context: ./
      dockerfile: ./envoy/Dockerfile
      args:
        - ENVOY_CONFIG=${ENVOY_CONFIG}
    ports:
      - "8081:8081"
      - "9090:9090"
    networks:
      - quickfeed_net

  quickfeed:
    container_name: quickfeed
    image: quickfeed/quickfeed
    build:
      context: ./
      dockerfile: ./Dockerfile
    links:
      - envoy
    ports:
      - "8080:8080"
    networks:
      - quickfeed_net

networks:
  quickfeed_net:
    ipam:
      config:
      - subnet: 172.20.0.0/16

