version: '3.8'
services:
  envoy:
    container_name: envoy
    image: quickfeed/envoy
    build:
      context: ./
      dockerfile: ./envoy/Dockerfile
      args:
        - DOMAIN=${DOMAIN}
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      # - "9901:9901" # envoy admin endpoint.
    networks:
      - quickfeed_net
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml

  quickfeed:
    container_name: quickfeed
    image: quickfeed/quickfeed
    build:
      context: ./
      dockerfile: ./Dockerfile
    links:
      - envoy
    # Uncomment to expose quickfeed ports for debugging on the host machine.
    # ports:
    #   - "8081:8081"
    #   - "9090:9090"
    networks:
      - quickfeed_net

networks:
  quickfeed_net:
    ipam:
      config:
      - subnet: 172.20.0.0/16

