[[constraint]]
  name = "github.com/gorilla/sessions"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/labstack/echo"

[[constraint]]
  branch = "master"
  name = "github.com/markbates/goth"

[[constraint]]
  name = "github.com/xanzy/go-gitlab"
  version = "0.5.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"
