apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gitwebhook
  namespace: default
spec:
  template:
    spec:
      containers:
      - # Replace for docker hub username
        image: docker.io/hanifff/test:hookKube
        env:
        - name: GITHUB_PERSONAL_TOKEN
          valueFrom:
            secretKeyRef:
              name: githubsecret
              key: personalAccessToken
        - name: WEBHOOK_SECRET
          valueFrom:
              secretKeyRef:
                name: githubsecret
                key: webhookSecret