apiVersion: v1
kind: ServiceAccount
metadata:
 name: agcicd
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: agcicd
  name: job-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete", "update","get", "watch", "list"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-role-ag
subjects:
- kind: ServiceAccount
  name: job-roles
  namespace: agcicd
roleRef:
  kind: ClusterRole
  name: job-role
  apiGroup: rbac.authorization.k8s.io
