apiVersion: v1
kind: ServiceAccount
metadata:
  name: agcicd

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-watcher
rules:
- apiGroups: [""] # "" indicate the core API group
  resources: ["nodes"]
  verbs: ["get", "watch", "list", "update"]
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: watch-nodes-global
subjects:
- kind: ServiceAccount
  name: agcicd
  namespace: default
roleRef:
  kind: ClusterRole
  name: node-watcher
  apiGroup: rbac.authorization.k8s.io